doc-warnings: true

ignore-paths:
    - doc
    - examples
    - test
    - utils

pylint:
    max-line-length: 140

pyflakes:
  run: false

pep257:
  run: true
  disable: 
    - D107
    - D212
    - D203
    - D204
